const DOCUMENT = "PAYMENTS_";

export default {
  CREATE: DOCUMENT + "SERVER:CREATE",
  CREATE_SUCCESS: DOCUMENT + "CREATE_SUCCESS",
  CREATE_FAILURE: DOCUMENT + "CREATE_FAILURE",

  GET: DOCUMENT + "SERVER:GET",
  GET_SUCCESS: DOCUMENT + "GET_SUCCESS",
  GET_FALURE: DOCUMENT + "GET_FAILURE",

  GET_ID: DOCUMENT + "SERVER:GET_ID",
  GET_ID_SUCCESS: DOCUMENT + "GET_ID_SUCCESS",
  GET_ID_FALURE: DOCUMENT + "GET_ID_FAILURE",

  SEARCH: DOCUMENT + "SERVER:SEARCH",
  SEARCH_SUCCESS: DOCUMENT + "SEARCH_SUCCESS",
  SEARCH_FALURE: DOCUMENT + "SEARCH_FALUR",

  SET_ORIGIN_ITEM: DOCUMENT + "SET_ORIGIN_ITEM",
};
