version: '3.7'

services:

  node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    container_name: feathers-api
    restart: unless-stopped
    tty: true
    links:
      - db
    depends_on:
      - db
    ports:
      - 3030:3030

  db:
    build:
      context: ./docker
    container_name: feathers-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - ./data:/var/lib/postgresql/data