const DOCUMENT = "ACCOUNT_";

export default {
  AUTH: DOCUMENT + "SERVER:AUTH",
  AUTH_SUCCESS: DOCUMENT + "AUTH_SUCCESS",
  AUTH_FAILURE: DOCUMENT + "AUTH_FAILURE",

  LOGOUT: DOCUMENT + "LOGOUT",
};
